### ISSUE TITLE
can't download book as pdf

### ISSUE THREAD

**Issue by mattsblack** [NamesJoeyWheeler/PearsonDL#2]
I got an "index out of range" error while trying to download my textbook as a pdf

L:\Desktop\PearsonDL>python PearsonDL.py -i 11300c2f-128e-44bf-a914-3c6216c66ed7 -p 561 -g -r
PearsonDL
Developed by NamesJoeyWheeler, FurryLovingMcNugget, and cdchris12
---------------------------------------------------
Downloading page images...
Page downloads complete!
Generating a PDF... (This may take a while)
Traceback (most recent call last):
  File "PearsonDL.py", line 130, in <module>
    main()
  File "PearsonDL.py", line 70, in main
    im0 = Image.open(f'{image_list[0]}').convert('RGB')
IndexError: list index out of range

**Comment by NamesJoeyWheeler** [comment]
Apologies for the late reply.
I tried this myself and it looks like it's an issue with the uuid.
Could you provide the link that contained the uuid?
Also, what is the book name?

**Comment by mattsblack** [comment]
the book name is Realidades 2 
The link for the uuid is: https://d38l3k3yaet8r2.cloudfront.net/resources/products/epubs/generated/11300c2f-128e-44bf-a914-3c6216c66ed7/foxit-assets/pages/page1?password=&accessToken=null&formMode=true

also whenever I try to download the page images without the pdf, the folder that it outputs to is empty.

**Comment by ghost** [comment]
Seems like Pearson decided to switch reader and now some books use Reader+ instead of the old one.
For what I have seen they now use jpg insted of png and xhtml.
pretty hard to fix by myself tho

**Comment by NamesJoeyWheeler** [comment]
Not sure if you still want to download the book, but if you do, the new version of PearsonDL may fix this issue.
