### ISSUE TITLE
Says successful but page images not visable. Using -g creates traceback error.

### ISSUE THREAD

**Issue by Benjamin5678** [NamesJoeyWheeler/PearsonDL#7]
When i just run it with the -i and -p it says it works but no images when I go the directory
```
D:\Downloads\PearsonDL-master>python PearsonDL.py -i c821f2c0-c623-482b-8110-d2c860807abb -p 1040
PearsonDL
Developed by NamesJoeyWheeler, FurryLovingMcNugget, and cdchris12
---------------------------------------------------
Downloading page images...
Page downloads complete!
--- Generated in 28.0317 seconds ---
```

When i run with -g there is a traceback error
```
D:\Downloads\PearsonDL-master>python PearsonDL.py -i c821f2c0-c623-482b-8110-d2c860807abb -p 1040 -g
PearsonDL
Developed by NamesJoeyWheeler, FurryLovingMcNugget, and cdchris12
---------------------------------------------------
Downloading page images...
Page downloads complete!
Generating a PDF... (This may take a while)
Traceback (most recent call last):
  File "D:\Downloads\PearsonDL-master\PearsonDL.py", line 130, in <module>
    main()
  File "D:\Downloads\PearsonDL-master\PearsonDL.py", line 70, in main
    im0 = Image.open(f'{image_list[0]}').convert('RGB')
IndexError: list index out of range
```
On widows for the record I might try in my linux dual boot and see if that has any better luck

Edit: Another thing is that I didnt see the manifest?password but I found a file named token. Maybe the different version of person works different? It worked without an error though so idk.

**Comment by NamesJoeyWheeler** [comment]
Apologies for the late reply.
This may work on the new version.
Could you post the Pearson document link here?

**Comment by FrexlDE** [comment]
Same problem here. I don't even receive any kind of error..

**Comment by DVDspacca** [comment]
Same problem here, everything seems to work, it says that images were downloaded, but nothing appears in the book folder.
